CREATE TABLE TRADING_DAY_T (
    TRADING_DAY CHAR(64),
    UPDATE_TIME CHAR(64)
);

CREATE TABLE ACCOUNT_T (
    ACCOUNT_ID CHAR(64),
    USER_ID CHAR(64),
    BALANCE DOUBLE,
    MARGIN DOUBLE,
    COMMISSION DOUBLE,
    OPENING_MARGIN DOUBLE,
    OPENING_COMMISSION DOUBLE,
    CLOSING_COMMISSION DOUBLE,
    AVAILABLE DOUBLE,
    POSITION_PROFIT DOUBLE,
    CLOSE_PROFIT DOUBLE,
    YD_BALANCE DOUBLE,
    TRADING_DAY CHAR(64),
    SETTLE_TIME CHAR(64)
);

CREATE TABLE TICK_T (
    INSTRUMENT_ID CHAR(64),
    LAST_PRICE DOUBLE,
    ASK_PRICE DOUBLE,
    BID_PRICE DOUBLE,
    ASK_VOLUME INT,
    BID_VOLUME INT,
    TODAY_VOLUME INT,
    OPEN_INSTEREST INT,
    OPEN_RPICE DOUBLE,
    CLOSE_PRICE DOUBLE,
    SETTLEMENT_PRICE DOUBLE,
    YD_CLOSE_PRICE DOUBLE,
    YD_SETTLEMENT_PRICE DOUBLE,
    UPDATE_TIME DOUBLE
);

CREATE TABLE TRANSACTION_T (
    TRANSACTION_ID CHAR(64),
    STRATEGY_ID CHAR(64),
    INSTRUMENT_ID CHAR(64),
    PRICE DOUBLE,
    VOLUME INT,
    OFFSET CHAR(64),
    DIRECTION CHAR(64),
    STATE CHAR(64),
    STATE_MESSAGE CHAR(64),
    TRADING_DAY CHAR(64),
    UPDATE_TIME CHAR(64)
);

CREATE TABLE ORDER_T (
    ORDER_ID CHAR(64),
    TRANSACTION_ID CHAR(64),
    INSTRUMENT_ID CHAR(64),
    PRICE DOUBLE,
    VOLUME DOUBLE,
    DIRECTION CHAR(64),
    OFFSET CHAR(64),
    TRADING_DAY CHAR(64)
);

CREATE TABLE TRADE_T (
    TRADE_ID CHAR(64),
    ORDER_ID CHAR(64),
    INSTRUMENT_ID CHAR(64),
    PRICE DOUBLE,
    VOLUME INT,
    DIRECTION CHAR(64),
    OFFSET CHAR(64),
    TRADING_DAY CHAR(64),
    UPDATE_TIME CHAR(64)
);

CREATE TABLE CONTRACT_T (
    CONTRACT_ID CHAR(64),
    USER_ID CHAR(64),
    INSTRUMENT_ID CHAR(64),
    DIRECTION CHAR(64),
    PRICE DOUBLE,
    CLOSE_PRICE DOUBLE,
    STATE CHAR(64),
    OPEN_TRADING_DAY CHAR(64),
    OPEN_TIME CHAR(64)
);

CREATE TABLE USER_T (
    USER_ID CHAR(64),
    PASSWORD CHAR(64),
    CREATE_TIME CHAR(64),
    LAST_LOGIN_TIME CHAR(64)
);

CREATE TABLE STRATEGY_PROFILE_T (
    STRATEGY_ID CHAR(64),
    USER_ID CHAR(64),
    PASSWORD CHAR(64),
    STATE CHAR(64),
    CREATE_DATE CHAR(64),
    REMOVE_DATE CHAR(64),
    INSTRUMENTS VARCHAR(1024),
    ARGS VARCHAR(1024)
);

CREATE TABLE INSTRUMENT_T (
    INSTRUMENT_ID CHAR(64),
    EXCHANGE_ID CHAR(64),
    MULTIPLE DOUBLE,
    AMOUNT_MARGIN DOUBLE,
    VOLUME_MARGIN DOUBLE,
    AMOUNT_COMMISSION DOUBLE,
    VOLUME_COMMISSION DOUBLE,
    UPDATE_TIME CHAR(64)
);

CREATE TABLE RISK_NOTICE_T (
    STRATEGY_ID CHAR(64),
    USER_ID CHAR(64),
    LEVEL INT,
    CODE INT,
    MESSAGE CHAR(64),
    UPDATE_TIME CHAR(64)
);
